var axios = require('axios')

try {

} catch
throw new Error('This is an error')


